package com.attendly.service;

import com.attendly.dto.StudentRequest;
import com.attendly.entity.Student;
import com.attendly.exception.ResourceAlreadyExistsException;
import com.attendly.exception.ResourceNotFoundException;
import com.attendly.repository.ClassRepository;
import com.attendly.repository.StudentRepository;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.attendly.service.EmailService;
import java.security.SecureRandom;
import java.util.Base64;

@Service
@RequiredArgsConstructor
public class StudentService {

  private final StudentRepository studentRepository;
  private final ClassRepository classRepository;
  private final PasswordEncoder passwordEncoder;
  private final EmailService emailService;

  @Transactional
  public Student createStudent(StudentRequest request, Long adminId) {
    // Check if email already exists
    if (studentRepository.existsByEmail(request.getEmail())) {
      throw new ResourceAlreadyExistsException(
          "Student with email " + request.getEmail() + " already exists");
    }

    // Check if roll number already exists
    if (studentRepository.existsByRollNumber(request.getRollNumber())) {
      throw new ResourceAlreadyExistsException(
          "Student with roll number " + request.getRollNumber() + " already exists");
    }

    // Check if registration number already exists (if provided)
    if (request.getRegistrationNumber() != null
        && !request.getRegistrationNumber().isEmpty()
        && studentRepository.existsByRegistrationNumber(request.getRegistrationNumber())) {
      throw new ResourceAlreadyExistsException(
          "Student with registration number "
              + request.getRegistrationNumber()
              + " already exists");
    }

    // Verify class exists
    classRepository
        .findByIdAndAdminId(request.getClassId(), adminId)
        .orElseThrow(
            () ->
                new ResourceNotFoundException("Class not found with id: " + request.getClassId()));

    // If password is not provided, generate a secure random initial password
    String initialPassword = request.getPassword();
    boolean generated = false;
    if (initialPassword == null || initialPassword.isEmpty()) {
      initialPassword = generateSecurePassword(10);
      generated = true;
    }

    Student student =
        Student.builder()
            .name(request.getName())
            .email(request.getEmail())
            .password(passwordEncoder.encode(initialPassword))
            .phone(request.getPhone())
            .rollNumber(request.getRollNumber())
            .registrationNumber(request.getRegistrationNumber())
            .classId(request.getClassId())
            .departmentId(request.getDepartmentId())
            .adminId(adminId)
            .isActive(true)
            .phoneVerified(false)
            .firstLogin(true)
            .build();

    Student saved = studentRepository.save(student);

    // Email initial password to student if it was generated by the server
    if (generated) {
      String subject = "Welcome to Attendly — your initial login details";
      String html = String.format(
          "<p>Hello %s,</p><p>Your account has been created. Use the following temporary password for first login:</p><p><strong>%s</strong></p><p>On first login you will be prompted to set your own password.</p>",
          saved.getName(), initialPassword);
      emailService.sendEmail(saved.getEmail(), subject, html);
    }

    return saved;
  }

  private String generateSecurePassword(int length) {
    SecureRandom rnd = new SecureRandom();
    byte[] bytes = new byte[length * 2];
    rnd.nextBytes(bytes);
    // Base64 encode then trim to requested length, removing non-alphanumeric characters is optional
    String encoded = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    // Ensure password has at least length characters
    return encoded.substring(0, Math.min(length, encoded.length()));
  }

  public List<Student> getAllStudents(Long adminId) {
    return studentRepository.findByAdminIdAndIsActive(adminId, true);
  }

  public List<Student> getStudentsByClass(Long classId, Long adminId) {
    // Verify class belongs to admin
    classRepository
        .findByIdAndAdminId(classId, adminId)
        .orElseThrow(() -> new ResourceNotFoundException("Class not found with id: " + classId));

    return studentRepository.findByClassIdAndIsActive(classId, true);
  }

  public Student getStudentById(Long id, Long adminId) {
    return studentRepository
        .findByIdAndAdminId(id, adminId)
        .orElseThrow(() -> new ResourceNotFoundException("Student not found with id: " + id));
  }

  @Transactional
  public Student updateStudent(Long id, StudentRequest request, Long adminId) {
    Student student = getStudentById(id, adminId);

    // Check if new email conflicts with another student
    if (!student.getEmail().equals(request.getEmail())
        && studentRepository.existsByEmail(request.getEmail())) {
      throw new ResourceAlreadyExistsException(
          "Student with email " + request.getEmail() + " already exists");
    }

    // Check if new roll number conflicts with another student
    if (!student.getRollNumber().equals(request.getRollNumber())
        && studentRepository.existsByRollNumber(request.getRollNumber())) {
      throw new ResourceAlreadyExistsException(
          "Student with roll number " + request.getRollNumber() + " already exists");
    }

    // Check if new registration number conflicts with another student
    if (request.getRegistrationNumber() != null
        && !request.getRegistrationNumber().isEmpty()
        && (student.getRegistrationNumber() == null
            || !student.getRegistrationNumber().equals(request.getRegistrationNumber()))
        && studentRepository.existsByRegistrationNumber(request.getRegistrationNumber())) {
      throw new ResourceAlreadyExistsException(
          "Student with registration number "
              + request.getRegistrationNumber()
              + " already exists");
    }

    // Verify class if changed
    if (!student.getClassId().equals(request.getClassId())) {
      classRepository
          .findByIdAndAdminId(request.getClassId(), adminId)
          .orElseThrow(
              () ->
                  new ResourceNotFoundException(
                      "Class not found with id: " + request.getClassId()));
    }

    student.setName(request.getName());
    student.setEmail(request.getEmail());
    if (request.getPassword() != null && !request.getPassword().isEmpty()) {
      student.setPassword(passwordEncoder.encode(request.getPassword()));
    }
    student.setPhone(request.getPhone());
    student.setRollNumber(request.getRollNumber());
    student.setRegistrationNumber(request.getRegistrationNumber());
    student.setClassId(request.getClassId());
    student.setDepartmentId(request.getDepartmentId());

    return studentRepository.save(student);
  }

  @Transactional
  public void deleteStudent(Long id, Long adminId) {
    Student student = getStudentById(id, adminId);
    student.setIsActive(false);
    studentRepository.save(student);
  }

  public List<Student> searchStudents(String query, Long classId) {
    return studentRepository
        .findByClassIdAndIsActiveAndNameContainingIgnoreCaseOrClassIdAndIsActiveAndRollNumberContainingIgnoreCase(
            classId, true, query, classId, true, query);
  }
}
