package com.attendly.service;

import com.attendly.dto.TeacherRequest;
import com.attendly.entity.Teacher;
import com.attendly.exception.ResourceAlreadyExistsException;
import com.attendly.exception.ResourceNotFoundException;
import com.attendly.repository.DepartmentRepository;
import com.attendly.repository.TeacherRepository;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.util.Base64;

@Service
@RequiredArgsConstructor
public class TeacherService {

  private final TeacherRepository teacherRepository;
  private final DepartmentRepository departmentRepository;
  private final PasswordEncoder passwordEncoder;
  private final EmailService emailService;

  @Transactional
  public Teacher createTeacher(TeacherRequest request, Long adminId) {
    // Check if email already exists
    if (teacherRepository.existsByEmail(request.getEmail())) {
      throw new ResourceAlreadyExistsException(
          "Teacher with email " + request.getEmail() + " already exists");
    }

    // Verify department exists
    if (request.getDepartmentId() != null) {
      departmentRepository
          .findByIdAndAdminId(request.getDepartmentId(), adminId)
          .orElseThrow(
              () ->
                  new ResourceNotFoundException(
                      "Department not found with id: " + request.getDepartmentId()));
    }

    // If password is not provided, generate a secure random initial password
    String initialPassword = request.getPassword();
    boolean generated = false;
    if (initialPassword == null || initialPassword.isEmpty()) {
      initialPassword = generateSecurePassword(10);
      generated = true;
    }

    Teacher teacher =
        Teacher.builder()
            .name(request.getName())
            .email(request.getEmail())
            .password(passwordEncoder.encode(initialPassword))
            .phone(request.getPhone())
            .departmentId(request.getDepartmentId())
            .adminId(adminId)
            .isActive(true)
            .firstLogin(true)
            .build();

    Teacher saved = teacherRepository.save(teacher);

    // Email initial password to teacher if it was generated by the server
    if (generated) {
      String subject = "Welcome to Attendly — your initial login details";
      String html = String.format(
          "<p>Hello %s,</p><p>Your teacher account has been created. Use the following temporary password for first login:</p><p><strong>%s</strong></p><p>On first login you will be prompted to set your own password.</p>",
          saved.getName(), initialPassword);
      emailService.sendEmail(saved.getEmail(), subject, html);
    }

    return saved;
  }

  private String generateSecurePassword(int length) {
    SecureRandom rnd = new SecureRandom();
    byte[] bytes = new byte[length * 2];
    rnd.nextBytes(bytes);
    // Base64 encode then trim to requested length
    String encoded = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    return encoded.substring(0, Math.min(length, encoded.length()));
  }

  public List<Teacher> getAllTeachers(Long adminId) {
    return teacherRepository.findByAdminIdAndIsActive(adminId, true);
  }

  public List<Teacher> getTeachersByDepartment(Long departmentId, Long adminId) {
    // Verify department belongs to admin
    departmentRepository
        .findByIdAndAdminId(departmentId, adminId)
        .orElseThrow(
            () -> new ResourceNotFoundException("Department not found with id: " + departmentId));

    return teacherRepository.findByDepartmentIdAndIsActive(departmentId, true);
  }

  public Teacher getTeacherById(Long id, Long adminId) {
    return teacherRepository
        .findByIdAndAdminId(id, adminId)
        .orElseThrow(() -> new ResourceNotFoundException("Teacher not found with id: " + id));
  }

  @Transactional
  public Teacher updateTeacher(Long id, TeacherRequest request, Long adminId) {
    Teacher teacher = getTeacherById(id, adminId);

    // Check if new email conflicts with another teacher
    if (!teacher.getEmail().equals(request.getEmail())
        && teacherRepository.existsByEmail(request.getEmail())) {
      throw new ResourceAlreadyExistsException(
          "Teacher with email " + request.getEmail() + " already exists");
    }

    // Verify department if changed
    if (request.getDepartmentId() != null
        && !request.getDepartmentId().equals(teacher.getDepartmentId())) {
      departmentRepository
          .findByIdAndAdminId(request.getDepartmentId(), adminId)
          .orElseThrow(
              () ->
                  new ResourceNotFoundException(
                      "Department not found with id: " + request.getDepartmentId()));
    }

    teacher.setName(request.getName());
    teacher.setEmail(request.getEmail());
    if (request.getPassword() != null && !request.getPassword().isEmpty()) {
      teacher.setPassword(passwordEncoder.encode(request.getPassword()));
    }
    teacher.setPhone(request.getPhone());
    teacher.setDepartmentId(request.getDepartmentId());

    return teacherRepository.save(teacher);
  }

  @Transactional
  public void deleteTeacher(Long id, Long adminId) {
    Teacher teacher = getTeacherById(id, adminId);
    teacher.setIsActive(false);
    teacherRepository.save(teacher);
  }

  public List<Teacher> searchTeachers(String query, Long adminId) {
    return teacherRepository
        .findByAdminIdAndIsActiveAndNameContainingIgnoreCaseOrAdminIdAndIsActiveAndEmailContainingIgnoreCase(
            adminId, true, query, adminId, true, query);
  }

  public List<Teacher> searchTeachersInDepartment(String query, Long departmentId) {
    return teacherRepository
        .findByDepartmentIdAndIsActiveAndNameContainingIgnoreCaseOrDepartmentIdAndIsActiveAndEmailContainingIgnoreCase(
            departmentId, true, query, departmentId, true, query);
  }
}
